# embeds a binary file as a c byte array header
# usage: cmake -dinput=<file> -doutput=<header> -dsymbol=<name> -p embed_binarycmake

file(READ "${INPUT}" HEX_CONTENT HEX)
string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1," BYTES "${HEX_CONTENT}")
file(WRITE "${OUTPUT}"
    "// generated by embed_binary.cmake - do not edit\n"
    "static const unsigned char ${SYMBOL}[] = {${BYTES}};\n"
    "static const unsigned int ${SYMBOL}_size = sizeof(${SYMBOL});\n")
